--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/snarerectify/BetterWardrobe
build-by-default: true
branches:
- main
projects:
  BetterWardrobe:
    path: ""
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
      - src: muqsit/invmenu/InvMenu
        version: ^4.6.4
      - src: poggit/libasynql/libasynql
        version: ^4.1.6
      - src: Jibix/Forms/Forms
        version: ^1.0
...
